setup.bat
setup.ps1

- .bat & Powershell script to simplify initial setup
- Prompts for MS2 location & database connection info
- Runs ingest + seeding projects

Add Powershell setup script

---

Maple2.File.Ingest/Mapper/AnimationMapper.cs
Maple2.Model/Metadata/AnimationMetadata.cs
Maple2.Model/Metadata/Constants.cs
Maple2.Server.Game/Commands/CoordCommand.cs
Maple2.Server.Game/Commands/NpcCommand.cs
Maple2.Server.Game/Commands/TriggerCommand.cs
Maple2.Server.Game/Manager/Field/AgentNavigation.cs
Maple2.Server.Game/Manager/Field/FieldManager.Trigger.cs
Maple2.Server.Game/Manager/Items/ItemManager.cs
Maple2.Server.Game/Maple2.Server.Game.csproj
Maple2.Server.Game/Model/Field/Actor/FieldNpc.cs
Maple2.Server.Game/Model/Field/Actor/Routine/AnimateRoutine.cs
Maple2.Server.Game/Model/Field/Entity/FieldTrigger.cs
Maple2.Server.Game/Trigger/TriggerContext.Npc.cs
dev.bat

Animation triggers
Spawn Npc triggers
Debugging commands

feat: Triggers

---

Maple2.Database/Storage/Metadata/ServerTableMetadataStorage.cs
Maple2.File.Ingest/Maple2.File.Ingest.csproj
Maple2.File.Ingest/Mapper/ServerTableMapper.cs
Maple2.Model/Maple2.Model.csproj.DotSettings
Maple2.Model/Metadata/ServerTable/InstanceFieldTable.cs
Maple2.Model/Metadata/ServerTable/JobConditionTable.cs
Maple2.Model/Metadata/ServerTable/ScriptConditionTable.cs
Maple2.Model/Metadata/ServerTable/ScriptFunctionTable.cs
Maple2.Model/Metadata/ServerTableMetadata.cs
Maple2.Server.Game/Manager/Field/FieldManager.Factory.cs

Should not be merged until new Maple2.File.Parser
Mentioning #14

Ingest Server Npc Talk/Script XMLs

---

Maple2.Database/Model/CharacterConfig.cs
Maple2.Database/Storage/Game/GameStorage.User.cs
Maple2.Database/Storage/Metadata/TableMetadataStorage.cs
Maple2.File.Ingest/Mapper/TableMapper.cs
Maple2.Model/Enum/EnchantResult.cs
Maple2.Model/Metadata/Constants.cs
Maple2.Model/Metadata/Table/LearningQuestTable.cs
Maple2.Model/Metadata/TableMetadata.cs
Maple2.Server.Game/Manager/Config/ConfigManager.cs
Maple2.Server.Game/Manager/ItemEnchantManager.cs
Maple2.Server.Game/Manager/NpcScriptManager.cs
Maple2.Server.Game/PacketHandlers/MasteryHandler.cs
Maple2.Server.Game/PacketHandlers/QuestHandler.cs
Maple2.Server.Game/PacketHandlers/RevivalHandler.cs
Maple2.Server.Game/Util/ConditionUtil.cs
Maple2.Server.World/Migrations/20240501000613_DeathPenalty.Designer.cs
Maple2.Server.World/Migrations/20240501000613_DeathPenalty.cs

- Implements Maple Guide #23 
- Added Death Penalty tracking

Feat: Maple Guide

---

Maple2.Server.Game/Manager/NpcScriptManager.cs

NpcTalk - Job Check on Script

---

Maple2.Database/Context/MetadataContext.cs
Maple2.Database/Storage/Metadata/ServerTableMetadataStorage.cs
Maple2.File.Ingest/Maple2.File.Ingest.csproj
Maple2.File.Ingest/Mapper/MapEntityMapper.cs
Maple2.File.Ingest/Mapper/NpcMapper.cs
Maple2.File.Ingest/Mapper/ServerTableMapper.cs
Maple2.Model/Enum/DropType.cs
Maple2.Model/Metadata/MapEntity/Breakable.cs
Maple2.Model/Metadata/NpcMetadata.cs
Maple2.Model/Metadata/ServerTable/GlobalDropItemBoxTable.cs
Maple2.Model/Metadata/ServerTable/IndividualDropItemTable.cs
Maple2.Model/Metadata/ServerTable/RoomRandomTable.cs
Maple2.Model/Metadata/ServerTableMetadata.cs
Maple2.Server.Game/Manager/Field/FieldManager.State.cs
Maple2.Server.Game/Manager/Field/FieldManager.cs
Maple2.Server.Game/Manager/Items/ItemDropManager.cs
Maple2.Server.Game/Manager/Items/ItemManager.cs
Maple2.Server.Game/Manager/MasteryManager.cs
Maple2.Server.Game/Manager/NpcScriptManager.cs
Maple2.Server.Game/Model/Field/Actor/Actor.cs
Maple2.Server.Game/Model/Field/Actor/FieldNpc.cs
Maple2.Server.Game/Model/Field/Entity/FieldItem.cs
Maple2.Server.Game/PacketHandlers/BreakableHandler.cs
Maple2.Server.Game/PacketHandlers/InteractObjectHandler.cs
Maple2.Server.Game/PacketHandlers/ItemPickupHandler.cs
Maple2.Server.Game/Packets/FieldPacket.cs
Maple2.Server.Game/Session/GameSession.cs
Maple2.Server.Game/Trigger/TriggerContext.Field.cs
Maple2.Server.Game/Util/ConditionUtil.cs

I'm not really fond of how ItemDropManager is on player. I think this has to be on the field instead, but it requires access to the ServerTableMetadataStorage. Any advice on how to tackle this would be appreciated

Item Drops

---

Maple2.Server.Game/Manager/BuddyManager.cs
Maple2.Server.Game/Manager/QuestManager.cs
Maple2.Server.Game/PacketHandlers/BreakableHandler.cs
Maple2.Server.Game/PacketHandlers/ItemUseHandler.cs
Maple2.Server.Game/PacketHandlers/NpcTalkHandler.cs
Maple2.Server.Game/PacketHandlers/UgcHandler.cs
Maple2.Server.Game/Trigger/TriggerContext.Field.cs
Maple2.Server.Game/Util/ConditionUtil.cs

- Adding more Quest and Achievement Condition support #33

More Quest/Achievement Conditions

---

Maple2.Model/Metadata/ServerTable/UserStatTable.cs
Maple2.Server.Game/Commands/PlayerCommand.cs
Maple2.Server.Game/Commands/WarpCommand.cs
Maple2.Server.Game/Manager/Field/FieldManager.State.cs
Maple2.Server.Game/Manager/Items/InventoryManager.cs
Maple2.Server.Game/Manager/QuestManager.cs
Maple2.Server.Game/Model/Field/Actor/FieldNpc.cs
Maple2.Server.Game/Model/Field/Actor/Routine/MoveRoutine.cs
Maple2.Server.Game/PacketHandlers/InteractObjectHandler.cs
Maple2.Server.Game/PacketHandlers/QuestHandler.cs
Maple2.Server.Game/Util/ConditionUtil.cs

- feat: goto command
- fix: item bind on loot
- fix: #56 
- fix: npc spawn without agent
- feat: animation routine for npcs

Feat: exploration & navigator quests

---

Maple2.File.Ingest/Maple2.File.Ingest.csproj
Maple2.File.Ingest/Mapper/AiMapper.cs
Maple2.Model/Enum/NpcAi.cs
Maple2.Model/Metadata/AiMetadata.cs
Maple2.Server.Game/Commands/NpcCommand.cs
Maple2.Server.Game/Manager/Field/FieldManager.cs
Maple2.Server.Game/Model/Field/Actor/Actor.cs
Maple2.Server.Game/Model/Field/Actor/ActorState/AiState.cs
Maple2.Server.Game/Model/Field/Actor/FieldNpc.cs
Maple2.Server.Game/Model/Field/Actor/FieldPlayer.cs
Maple2.Server.Game/Model/Field/Actor/IActor.cs
Maple2.Server.Game/Packets/NpcNotice.cs
Maple2.Server.Game/Packets/RoomTimer.cs
Maple2.Server.Game/Packets/TriggerPacket.cs
Maple2.Server.Game/Session/GameSession.cs

refactored ai data mapper to use ochi's schema
made ai debug info command less annoying to type
added Field.TickCount (use this, not Environment.TickCount)
added IActor.CastSkill (not full functionality, just a placeholder for now)
added ai state machine to traverse the ai scripts (missing a lot of functionality)
added debug print message chat bubbles to FieldNpc
added NpcNotice packet

first draft of mob state machine implementation

---

Maple2.Database/Storage/Metadata/MapEntityStorage.cs
Maple2.File.Ingest/Mapper/MapEntityMapper.cs
Maple2.Model/Metadata/MapEntity/MapEntity.cs
Maple2.Model/Metadata/MapEntity/PatrolData.cs
Maple2.Model/Metadata/MapEntity/SpawnPoint.cs
Maple2.Model/Metadata/MapEntityMetadata.cs
Maple2.Server.Game/Manager/Field/FieldManager.State.cs
Maple2.Server.Game/Manager/Field/FieldManager.cs
Maple2.Server.Game/Model/Field/Actor/FieldNpc.cs
start.bat

I feel like putting the patrol logic on top of the NextRoutine made sense but kinda wished for a better place, any suggestions?

feat: npc patrol data

---

Maple2.Model/Enum/Party.cs
Maple2.Model/Game/Party/Party.cs
Maple2.Model/Game/Party/PartyInvite.cs
Maple2.Model/Game/Party/PartyVote.cs
Maple2.Model/Metadata/Constants.cs
Maple2.Server.Core/proto/channel/channel.proto
Maple2.Server.Core/proto/world/world.proto
Maple2.Server.Game/Manager/PartyManager.cs
Maple2.Server.Game/PacketHandlers/PartyHandler.cs
Maple2.Server.Game/Packets/PartyPacket.cs
Maple2.Server.Game/Service/ChannelService.Party.cs
Maple2.Server.World/Containers/PartyManager.cs
Maple2.Server.World/Service/WorldService.Party.cs

- Closes #10 
- Fix on disbanding party 1 member leaves in a party member count of 2.

Party Ready Check

---

Maple2.Model/Game/Party/PartyVote.cs
Maple2.Server.Core/proto/channel/channel.proto
Maple2.Server.Core/proto/world/world.proto
Maple2.Server.Game/Manager/PartyManager.cs
Maple2.Server.Game/PacketHandlers/PartyHandler.cs
Maple2.Server.Game/Packets/PartyPacket.cs
Maple2.Server.Game/Service/ChannelService.Party.cs
Maple2.Server.World/Containers/PartyManager.cs
Maple2.Server.World/Service/WorldService.Party.cs

- #11 
- Currently the time displayed in the Vote Kick is not correct. It, for some reason, displays a different time for every group member. Need to figure out what the correct time is.

Party Vote Kick

---

Maple2.Model/Enum/Party.cs
Maple2.Model/Error/PartySearchError.cs
Maple2.Model/Game/Party/Party.cs
Maple2.Model/Game/Party/PartySearch.cs
Maple2.Model/Metadata/Constants.cs
Maple2.Server.Core/Constants/RecvOp.cs
Maple2.Server.Core/Constants/SendOp.cs
Maple2.Server.Core/proto/channel/channel.proto
Maple2.Server.Core/proto/common.proto
Maple2.Server.Core/proto/world/world.proto
Maple2.Server.Game/Manager/PartyManager.cs
Maple2.Server.Game/PacketHandlers/PartyHandler.cs
Maple2.Server.Game/PacketHandlers/PartySearchHandler.cs
Maple2.Server.Game/Packets/PartyPacket.cs
Maple2.Server.Game/Packets/PartySearchPacket.cs
Maple2.Server.Game/Service/ChannelService.PartySearch.cs
Maple2.Server.World/Containers/PartyLookup.cs
Maple2.Server.World/Containers/PartyManager.cs
Maple2.Server.World/Containers/PartySearchLookup.cs
Maple2.Server.World/Containers/PartySearchManager.cs
Maple2.Server.World/Program.cs
Maple2.Server.World/Service/WorldService.Party.cs
Maple2.Server.World/Service/WorldService.PartySearch.cs
Maple2.Server.World/Service/WorldService.cs

Party Finder

---

Maple2.Server.Core/proto/world/world.proto
Maple2.Server.Game/PacketHandlers/ResponseKeyHandler.cs
Maple2.Server.Game/Session/GameSession.cs
Maple2.Server.World/Service/WorldService.Migrate.cs

fix: multiple channels

---

Maple2.Server.Game/Packets/CinematicPacket.cs
Maple2.Server.Game/Trigger/TriggerContext.Cinematic.cs

finally can reach peak lore info

Fix cinematic talk duration

---

Maple2.Server.Game/Model/Field/Actor/FieldPlayer.cs
Maple2.Server.Game/Model/Skill/SkillRecord.cs
Maple2.Server.Game/PacketHandlers/FallDamageHandler.cs
Maple2.Server.Game/PacketHandlers/SkillHandler.cs
Maple2.Server.Game/Session/GameSession.cs
Maple2.Server.Game/Util/ConditionUtil.cs

Updating is just based on field tickCount and not an async task, might be better to have long-running regens be in another thread.

Add spirit & stamina consumption

---

Maple2.File.Ingest/Generator/TriggerGenerator.cs
Maple2.File.Ingest/Utils/PyParameter.cs
Maple2.File.Ingest/Utils/Trigger/IScriptBlock.cs
Maple2.File.Ingest/Utils/Trigger/TriggerApiScript.cs
Maple2.File.Ingest/Utils/Trigger/TriggerScript.Action.cs
Maple2.File.Ingest/Utils/Trigger/TriggerScript.Condition.cs
Maple2.File.Ingest/Utils/Trigger/TriggerScript.State.cs
Maple2.File.Ingest/Utils/Trigger/TriggerScript.Transition.cs
Maple2.File.Ingest/Utils/Trigger/TriggerScript.cs
Maple2.File.Ingest/Utils/TriggerDefinitionOverride.cs

who knows...
this is the diff it generates: https://github.com/kOchirasu/Maple2-GeneratedScripts/commit/3970e83778f3cbb9cc4b3ec8866a0c85efdba958

More improvements to trigger script generation

---

Maple2.File.Ingest/Mapper/MapEntityMapper.cs
Maple2.Model/Metadata/MapEntity/SpawnPoint.cs
Maple2.Server.Game/Manager/Field/FieldManager.cs
Maple2.Server.Game/Trigger/TriggerContext.Npc.cs

Requires re-running Maple2.File.Ingest

Use correct NPC count for spawning

---

Maple2.Server.Game/Manager/Field/FieldManager.State.cs
Maple2.Server.Game/Manager/Field/FieldManager.cs
Maple2.Server.Game/Model/Field/Entity/FieldLiftable.cs
Maple2.Server.Game/PacketHandlers/RequestCubeHandler.cs
Maple2.Server.Game/Packets/CubePacket.cs
Maple2.Server.Game/Packets/LiftablePacket.cs
Maple2.Server.Game/Trigger/TriggerContext.Field.cs
Maple2.Server.Game/Util/ConditionUtil.cs

Fixes liftables despawning & respawning incorrectly. Also implements the DetectLiftable trigger condition.

Add liftable check & fix spawning

---

Maple2.Database/Context/Ms2Context.cs
Maple2.Database/Model/Market/BlackMarketListing.cs
Maple2.Database/Storage/Game/GameStorage.Market.cs
Maple2.Database/Storage/Metadata/TableMetadataStorage.cs
Maple2.File.Ingest/Maple2.File.Ingest.csproj
Maple2.File.Ingest/Mapper/ItemMapper.cs
Maple2.File.Ingest/Mapper/TableMapper.cs
Maple2.Model/Enum/BlackMarketSort.cs
Maple2.Model/Error/BlackMarketError.cs
Maple2.Model/Game/Market/BlackMarketListing.cs
Maple2.Model/Metadata/ItemMetadata.cs
Maple2.Model/Metadata/Table/BlackMarketTable.cs
Maple2.Model/Metadata/TableMetadata.cs
Maple2.Server.Core/proto/world/world.proto
Maple2.Server.Game/Commands/ItemCommand.cs
Maple2.Server.Game/Manager/BlackMarketManager.cs
Maple2.Server.Game/PacketHandlers/BlackMarketHandler.cs
Maple2.Server.Game/Packets/BlackMarketPacket.cs
Maple2.Server.Game/Session/GameSession.cs
Maple2.Server.Tests/Game/Manager/Item/ItemCollectionTest.cs
Maple2.Server.World/Containers/BlackMarketLookup.cs
Maple2.Server.World/Migrations/20230911045230_SkillCooldown.cs
Maple2.Server.World/Migrations/20231002044140_UgcMarket.cs
Maple2.Server.World/Migrations/20240519031103_BlackMarket.Designer.cs
Maple2.Server.World/Migrations/20240519031103_BlackMarket.cs
Maple2.Server.World/Program.cs
Maple2.Server.World/Service/WorldService.BlackMarket.cs
Maple2.Server.World/Service/WorldService.cs

- Black Market adding and searching added.
- Fixes #27 
- ~Searching for stats is not yet implemented, will come in part 2.~ Fixes #29 
- Deleting listings and getting mail will be added in part 2 #28 
- Will need new version of Maple2.File.Parser so don't merge until that's available.

Black Market - Part 1

---

Maple2.File.Ingest/Mapper/MapEntityMapper.cs

Fix NPC spawn counts

---

Maple2.Server.Game/Trigger/TriggerContext.Npc.cs
Maple2.Server.Game/Util/ConditionUtil.cs

Also fixes emotion integers check

Fix MonsterDead condition

---

Maple2.Server.Game/Trigger/TriggerContext.Player.cs

Small fix for conditions that check multiple quests.

Fix early return on QuestUserDetected

---

Maple2.Server.Game/Model/Field/Actor/FieldPlayer.cs
Maple2.Server.Game/PacketHandlers/FallDamageHandler.cs
Maple2.Server.Game/PacketHandlers/RideSyncHandler.cs
Maple2.Server.Game/PacketHandlers/UserSyncHandler.cs
Maple2.Server.Game/Session/GameSession.cs
Maple2.Server.Game/Util/ConditionUtil.cs

Tracks distance & time for various ActorStates. There may be a few more conditions I wasn't able to find.

Add StateSync tracking

---

Maple2.Model/Game/TriggerObject.cs
Maple2.Server.Game/Model/Field/Entity/FieldInteract.cs

Adds some leeway to very tight box detects.
Also fixes interacts with 0 reset time from being reset.

Fix box detection & Interact reset

---

Maple2.File.Ingest/Utils/Trigger/TriggerScript.Condition.cs
Maple2.File.Ingest/Utils/TriggerDefinitionOverride.cs
Maple2.Server.Game/Trigger/TriggerContext.cs

Related scripts PR: https://github.com/kOchirasu/maple2-scripts/pull/6

Fix RandomCondition & object_interacted

---

Maple2.Server.Game/Manager/Field/FieldManager.State.cs
Maple2.Server.Game/Trigger/TriggerContext.Npc.cs

These all need to target mobs & npcs

Add fix for NPC triggers

---

Maple2.Database/Context/MetadataContext.cs
Maple2.Database/Storage/Metadata/TableMetadataStorage.cs
Maple2.File.Ingest/Maple2.File.Ingest.csproj
Maple2.File.Ingest/Mapper/QuestMapper.cs
Maple2.File.Ingest/Mapper/TableMapper.cs
Maple2.Model/Enum/Quest.cs
Maple2.Model/Enum/QuestState.cs
Maple2.Model/Metadata/QuestMetadata.cs
Maple2.Model/Metadata/Table/ChangeJobTable.cs
Maple2.Model/Metadata/TableMetadata.cs
Maple2.Model/ModelExtensions.cs
Maple2.Server.Game/Commands/PlayerCommand.cs
Maple2.Server.Game/Manager/ExperienceManager.cs
Maple2.Server.Game/Manager/QuestManager.cs
Maple2.Server.Game/PacketHandlers/QuestHandler.cs

Do not merge until new Maple2.File is updated to have changejob.xml parsed

Handle Job Awakening and Quest Exp

---

Maple2.Database/Model/CharacterConfig.cs
Maple2.Database/Storage/Game/GameStorage.User.cs
Maple2.Database/Storage/Metadata/TableMetadataStorage.cs
Maple2.File.Ingest/Mapper/TableMapper.cs
Maple2.Model/Enum/Reputation.cs
Maple2.Model/Enum/SkillPointSource.cs
Maple2.Model/Game/User/SkillPoint.cs
Maple2.Model/Metadata/Table/ChapterBookTable.cs
Maple2.Model/Metadata/TableMetadata.cs
Maple2.Server.Game/Commands/PlayerCommand.cs
Maple2.Server.Game/Manager/AchievementManager.cs
Maple2.Server.Game/Manager/Config/ConfigManager.cs
Maple2.Server.Game/Manager/QuestManager.cs
Maple2.Server.Game/PacketHandlers/UserChatHandler.cs
Maple2.Server.Game/Packets/SkillPointPacket.cs
Maple2.Server.Game/Packets/UserEnvPacket.cs
Maple2.Server.Game/Session/GameSession.cs
Maple2.Server.World/Migrations/20240528031038_SkillPoints.Designer.cs
Maple2.Server.World/Migrations/20240528031038_SkillPoints.cs

- Implements added skill points from quest/chapters and trophies
- Implements giving rewards for completing a chapter.
- Implements command to give skill points.

Skill Points & Chapter Rewards

---

Maple2.Server.Core/Network/Session.cs
Maple2.Server.Game/appsettings.json
Maple2.Tools/Extensions/StringExtension.cs
Maple2.Tools/Maple2.Tools.csproj

make sure to change `"restrictedToMinimumLevel": "Verbose"`  in Maple2.Server.Game\appsettings.json in WriteTo - Console object to see the changes

prettier packet logging

---

Maple2.Database/Storage/Metadata/MapEntityStorage.cs
Maple2.File.Ingest/Mapper/MapEntityMapper.cs
Maple2.Model/Metadata/MapEntity/Liftable.cs
Maple2.Model/Metadata/MapEntity/MapEntity.cs
Maple2.Model/Metadata/MapEntityMetadata.cs
Maple2.Server.Game/PacketHandlers/RequestCubeHandler.cs

feat: liftable target boxes

---

Maple2.Server.Game/Manager/NpcScriptManager.cs
Maple2.Server.Game/PacketHandlers/NpcTalkHandler.cs
Maple2.Server.Game/Util/NpcTalkUtil.cs

- Moved a few functions out of NpcScriptManager in order to get and set the proper metadata beforehand in edgecases where the first script is a quest script _and_ has script functions

Npc Talk fixes

---

.github/workflows/dotnet.yml
Maple2.Database/Storage/Metadata/TableMetadataStorage.cs
Maple2.File.Ingest/Maple2.File.Ingest.csproj
Maple2.File.Ingest/Mapper/TableMapper.cs
Maple2.Model/Metadata/Table/WorldMapTable.cs
Maple2.Model/Metadata/TableMetadata.cs
Maple2.Server.Game/Maple2.Server.Game.csproj
Maple2.Server.Game/PacketHandlers/TaxiHandler.cs
Maple2.Server.Game/Packets/TaxiPacket.cs
Maple2.Server.Game/Program.cs
Maple2.Server.Game/Util/WorldMapGraphStorage.cs
Maple2.Server.Tests/Game/Manager/Item/ItemCollectionTest.cs
Maple2.Server.Tests/Game/Util/WorldMapGraphTest.cs
Maple2.Server.Tests/Maple2.Server.Tests.csproj
Maple2.Server.Tests/Tools/Collision/CircleTests.cs
Maple2.Server.Tests/Tools/Collision/HoleCircleTest.cs
Maple2.Server.Tests/Tools/Collision/RectangleTests.cs
Maple2.Server.Tests/Tools/Collision/TrapezoidTests.cs
Maple2.Server.Tests/Usings.cs

- Resolves #55 
Need to wait for these pull requests to get merged
- https://github.com/AngeloTadeucci/Maple2.File/pull/19
- https://github.com/kOchirasu/Maple2.Lua/pull/3

Feat: calculate taxi cost

---

Maple2.Database/Context/MetadataContext.cs
Maple2.File.Ingest/Mapper/NpcMapper.cs
Maple2.File.Ingest/Mapper/PetMapper.cs
Maple2.File.Ingest/Mapper/SkillMapper.cs
Maple2.Model/Enum/Skill.cs
Maple2.Model/Metadata/Constants.cs
Maple2.Model/Metadata/NpcMetadata.cs
Maple2.Model/Metadata/PetMetadata.cs
Maple2.Model/Metadata/SkillMetadata.cs
Maple2.Server.Game/Commands/NpcCommand.cs
Maple2.Server.Game/Commands/PetCommand.cs
Maple2.Server.Game/Manager/Field/FieldManager.State.cs
Maple2.Server.Game/Model/Field/Actor/ActorStateComponent/AiState.cs
Maple2.Server.Game/Model/Field/Actor/ActorStateComponent/AnimationState.cs
Maple2.Server.Game/Model/Field/Actor/ActorStateComponent/BattleState.cs
Maple2.Server.Game/Model/Field/Actor/FieldNpc.cs
Maple2.Server.Game/Model/Field/Actor/FieldPet.cs
Maple2.Server.Game/PacketHandlers/SkillHandler.cs
Maple2.Server.Game/Util/ConditionUtil.cs

- Rough pet AI 
- Pet command to spawn hungry pets
- Fixed some achieve/quest conditions

WIP Hungry pet AI

---

Maple2.Model/Enum/ConditionType.cs
Maple2.Model/Enum/ExpType.cs
Maple2.Model/Enum/GameEventUserValueType.cs
Maple2.Model/Enum/InsigniaConditionType.cs
Maple2.Model/Enum/LiquidType.cs
Maple2.Model/Enum/NpcAi.cs
Maple2.Model/Enum/SystemBanner.cs
Maple2.Server.Core/Packets/UgcPacket.cs
Maple2.Server.Game/Model/Stats.cs
Maple2.Server.Game/PacketHandlers/LoadUgcMapHandler.cs
Maple2.Server.Game/PacketHandlers/UserSyncHandler.cs
Maple2.Server.Game/Packets/HomeCommandPacket.cs
Maple2.Server.Game/Packets/JobPacket.cs
Maple2.Server.Game/Packets/NpcNoticePacket.cs
Maple2.Server.Game/Packets/PartyPacket.cs
Maple2.Server.Game/Packets/TriggerPacket.cs
Maple2.Server.Game/Packets/WorldMapPacket.cs
Maple2.Server.Game/Scripting/Trigger/TriggerScriptLoader.cs
Maple2.Server.World/Service/WorldService.Migrate.cs

- Support chained shared script imports
- Cache shared scripts
- Misc cleanup for style

TriggerScriptLoader refactor

---

Maple2.Model/Game/Guild/GuildMember.cs
Maple2.Model/Metadata/Constants.cs
Maple2.Server.Core/PacketHandlers/LogSendHandler.cs
Maple2.Server.Core/proto/channel/channel.proto
Maple2.Server.Core/proto/world/world.proto
Maple2.Server.Game/Manager/ExperienceManager.cs
Maple2.Server.Game/Manager/GuildManager.cs
Maple2.Server.Game/PacketHandlers/GuildHandler.cs
Maple2.Server.Game/PacketHandlers/UgcHandler.cs
Maple2.Server.Game/Packets/GuildPacket.cs
Maple2.Server.Game/Scripting/Trigger/TriggerScriptLoader.cs
Maple2.Server.Game/Service/ChannelService.Guild.cs
Maple2.Server.Game/Util/ConditionUtil.cs
Maple2.Server.Web/Controllers/GuildController.cs
Maple2.Server.World/Containers/ClubManager.cs
Maple2.Server.World/Containers/GuildLookup.cs
Maple2.Server.World/Containers/GuildManager.cs
Maple2.Server.World/Service/WorldService.Guild.cs
Maple2.Server.World/Service/WorldService.Party.cs

Emblem doesn't actually work because idk what UGC changes are needed.

Handlers for Guild CheckIn, UpdateLeader, UpdateNotice, UpdateEmblem

---

Maple2.Database/Context/Ms2Context.cs
Maple2.Database/Model/Medal.cs
Maple2.Database/Storage/Game/GameStorage.Item.cs
Maple2.Database/Storage/Game/GameStorage.Medal.cs
Maple2.Database/Storage/Game/GameStorage.cs
Maple2.Database/Storage/Metadata/TableMetadataStorage.cs
Maple2.File.Ingest/Maple2.File.Ingest.csproj
Maple2.File.Ingest/Mapper/TableMapper.cs
Maple2.Model/Enum/MedalType.cs
Maple2.Model/Game/Item/ItemType.cs
Maple2.Model/Game/Medal.cs
Maple2.Model/Metadata/Table/SurvivalSkinInfoTable.cs
Maple2.Model/Metadata/TableMetadata.cs
Maple2.Server.Game/Manager/Items/InventoryManager.cs
Maple2.Server.Game/Manager/SurvivalManager.cs
Maple2.Server.Game/PacketHandlers/SurvivalHandler.cs
Maple2.Server.Game/Packets/SurvivalPacket.cs
Maple2.Server.Game/Session/GameSession.cs
Maple2.Server.World/Migrations/20240610051805_Medal.Designer.cs
Maple2.Server.World/Migrations/20240610051805_Medal.cs
Maple2.Server.World/Migrations/20240610175759_Medal.Designer.cs
Maple2.Server.World/Migrations/20240610175759_Medal.cs
Maple2.Server.World/Migrations/Ms2ContextModelSnapshot.cs

- Implements MKR medals creating, saving, equipping, and unequipping.
I'm not really content with how I handled equipped Medals, specifically when no medal is equipped. 
Any suggestions highly appreciated :)

Survival Medals

---

Maple2.File.Ingest/Mapper/AchievementMapper.cs
Maple2.File.Ingest/Mapper/QuestMapper.cs
Maple2.Server.Game/Manager/Field/FieldManager.cs
Maple2.Server.Game/Manager/QuestManager.cs
Maple2.Server.Game/Model/Field/Actor/ActorStateComponent/MovementStateTasks/MovementState.CleanupTask.cs
Maple2.Server.Game/Model/Field/Actor/FieldNpc.cs
Maple2.Server.Game/Model/Field/Actor/Routine/MoveRoutine.cs
Maple2.Server.Game/Trigger/TriggerContext.Npc.cs

- Sets default value of quest and achievement conditions to 1
- Fix: Set patrol data

Quest/Achievement Condition Fix and Patrol Fix

---

Maple2.Server.Game/Model/Field/Actor/ActorStateComponent/AnimationState.cs

This may not be fully correct in the end and will need to investigate further. In the mean time I would think this solves some more possibilities of missing idle anim.

Fix: Get idle Animation

---

Maple2.Server.Game/PacketHandlers/ItemDismantleHandler.cs

- added check for Gacha or Locked items that should not be dismantle-able
- Fix: #148

Fix: AutoAdd in Dismantle (#148)

---

Maple2.Server.Game/Model/Field/Actor/ActorStateComponent/MovementState.cs
Maple2.Server.Game/Model/Field/Actor/ActorStateComponent/MovementStateStates/MovementState.Walk.cs
Maple2.Server.Game/Model/Field/Actor/ActorStateComponent/MovementStateTasks/MovementState.EmoteTask.cs
Maple2.Server.Game/Model/Field/Actor/ActorStateComponent/MovementStateTasks/MovementState.SkillCastTask.cs

Cleanup: Remove substate on MovementState

---

Maple2.File.Ingest/Utils/PyParameter.cs
Maple2.File.Ingest/Utils/Trigger/TriggerApiScript.cs
Maple2.File.Ingest/Utils/Trigger/TriggerScript.cs
Maple2.File.Ingest/Utils/TriggerDefinitionOverride.cs
Maple2.Model/Enum/BannerType.cs
Maple2.Server.Game/Manager/Field/FieldManager.Trigger.cs
Maple2.Server.Game/Model/Field/TickTimer.cs
Maple2.Server.Game/Packets/MassiveEventPacket.cs
Maple2.Server.Game/Scripting/Trigger/TriggerContext.cs
Maple2.Server.Game/Scripting/Trigger/TriggerEnums.cs
Maple2.Server.Game/Trigger/TriggerContext.Field.cs
Maple2.Server.Game/Trigger/TriggerContext.Interface.cs
Maple2.Server.Game/Trigger/TriggerContext.MiniGame.cs
Maple2.Server.Game/Trigger/TriggerContext.Player.cs

- Also some misc renaming on some trigger functions.

Triggers: Adjust SetEventUi & SetMesh delay, implement SetState/UseState

---

Maple2.Database.Seed/Program.cs
Maple2.File.Ingest/Mapper/ServerTableMapper.cs
Maple2.File.Ingest/Utils/TriggerDefinitionOverride.cs
Maple2.Server.Game/Trigger/TriggerContext.Field.cs

- Fix: https://github.com/AngeloTadeucci/Maple2/issues/195

Trigger Function "SetEffect" arg1 null safe + fixes

---

Maple2.Database.Seed/Program.cs
Maple2.File.Ingest/Mapper/ServerTableMapper.cs
Maple2.Model/Enum/AttendGift.cs
Maple2.Model/Game/Event/GameEvent.cs
Maple2.Model/Metadata/ServerTable/GameEventTable.cs
Maple2.Server.Core/Packets/GameEventPacket.cs
Maple2.Server.Core/proto/channel/channel.proto
Maple2.Server.Game/GameServer.cs
Maple2.Server.Game/Service/ChannelService.GameEvent.cs
Maple2.Server.Game/Session/GameSession.cs
Maple2.Server.Login/PacketHandlers/LoginHandler.cs
Maple2.Server.Login/PacketHandlers/ServerEnterHandler.cs
Maple2.Server.World/Migrations/20240709075218_RemoveGameEvent.Designer.cs
Maple2.Server.World/Migrations/20240709075218_RemoveGameEvent.cs
Maple2.Server.World/WorldServer.cs

- Add scheduling and removing upcoming new events, ending events
- Removed game-event table as this is no longer needed
- Fixes and changes in ServerTableMapper for ingesting GameEvent

Game Event Rework - Pt 2

---

.env.example
Maple2.Database.Seed/docker-entrypoint.sh
Maple2.Server.Game/Dockerfile
Maple2.Server.Login/Dockerfile
Maple2.Server.Web/Dockerfile
Maple2.Server.World/Dockerfile
Maple2.Tools/Dotenv.cs
compose.yml

- Copy `.env.example` to `.env`
- Set `MS2_DATA_FOLDER` and rename it to `MS2_DOCKER_DATA_FOLDER`
```sh
docker compose run --rm -it db-seed
```
```sh
docker compose run --rm file-ingest
```
```sh
docker compose up login world game-main
```

﻿Update docker files

---

Maple2.File.Ingest/Mapper/ItemMapper.cs
Maple2.File.Ingest/Mapper/MapEntityMapper.cs
Maple2.File.Ingest/Mapper/NpcMapper.cs
Maple2.File.Ingest/Mapper/ServerTableMapper.cs
Maple2.File.Ingest/Program.cs
Maple2.Server.Game/Manager/ShopManager.cs

Filter items with not metadata from being added to the shop metadata
- Fix: #501

fix: Infinite loop in shop manager
